name = "roi-plus-api"
main = "src/index.ts"
compatibility_date = "2026-10-09"

[[d1_databases]]
binding = "DB"
database_name = "roi-plus"
database_id = "1341e66e-2e13-4051-8a2d-b89eab26337e"
migrations_dir = "../../db/migrations"

[triggers]
crons = ["*/10 * * * *"]

[vars]
ENABLE_AUTO_BET = "false"
ENABLE_BOATRACE_ODDS_SCRAPE = "true"
